### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by whatsdis** [ubergeek42/lambda-letsencrypt#12]
Each domain you want to manage can be configured to validate using either of
these methods.

> Do you want to configure HTTP validation[Y/n]? Y
> Do you want to create a bucket for these challenges(Choose No to select an existing bucket)[Y/n]? Y

CloudFront Configuration
Traceback (most recent call last):
  File "wizard.py", line 546, in <module>
    wizard(global_config)
  File "wizard.py", line 519, in wizard
    wizard_cf(global_config)
  File "wizard.py", line 188, in wizard_cf
    cf_dist_list = cloudfront.list_distributions()
  File "/root/lambda-letsencrypt/installer/cloudfront.py", line 9, in list_distributions
    for dist in dl['DistributionList']['Items']:
KeyError: 'Items'

**Comment by ubergeek42** [comment]
Let me know if that fixes it for you.
