### ISSUE TITLE
Error 404 in get_user -> register

### ISSUE THREAD

**Issue by fregante** [ubergeek42/lambda-letsencrypt#16]
I never used letsencrypt before and was hoping to let this take care of itself with the creation and updating of the certificate, but when trying to run the generated lambda function, I get this error:

``` log
START RequestId: f31cb3e2-339f-11e6-a2f7-139f7c45a328 Version: $LATEST
[INFO]  2016-06-16T08:54:36.788Z    f31cb3e2-339f-11e6-a2f7-139f7c45a328    No certificate exists for E2EDQ498I94TP2
[INFO]  2016-06-16T08:54:37.350Z    f31cb3e2-339f-11e6-a2f7-139f7c45a328    Creating user and key
HTTP Error 404: Not Found: HTTPError
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 570, in lambda_handler
    user = get_user()
  File "/var/task/lambda_function.py", line 80, in get_user
    user.register(cfg.EMAIL)
  File "/var/task/simple_acme.py", line 175, in register
    "mailto:{}".format(email)
  File "/var/task/simple_acme.py", line 46, in _send_signed_request
    LE_NONCE = urlopen(cfg.DIRECTORY_URL + "/directory").headers['Replay-Nonce']
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found

END RequestId: f31cb3e2-339f-11e6-a2f7-139f7c45a328
REPORT RequestId: f31cb3e2-339f-11e6-a2f7-139f7c45a328  Duration: 3819.12 ms    Billed Duration: 3900 ms    Memory Size: 128 MB Max Memory Used: 72 MB
```

This is my configuration:

```
**Summary**
Notification Email:                              -------@------
S3 Config Bucket:                                ---.----.com (existing)
IAM Role Name:                                   lambda-letsencrypt (to be created)
Support HTTP Challenges:                         True
S3 HTTP Challenge Bucket:                        ---.----.com (existing)
Domains To Manage With Lets-Encrypt
    ---.----.com - []
CloudFront Distributions To Manage:
    E0000000000000 - [---.----.com]
Elastic Load Balancers to Manage:
> Are these settings correct[Y/n]? y

Making Requested Changes
Creating SNS Topic for Notifications ✓
Role doesn't exist, attempting to create
Creating Role 'lambda-letsencrypt-test-role'
Role Created
Role policy doesn't exist, attempting to create
Writing Configuration File ✓
Creating Zip File To Upload To Lambda
    Adding 'lambda_function.py'
    Adding 'simple_acme.py'
    Adding 'config.py'
Zip File Created Successfully
Configuring Lambda Function:
    IAM ARN: arn:aws:iam::000000000000:role/lambda-letsencrypt/lambda-letsencrypt-test-role
    Uploading Function ✓
```

Also I didn't find any new files in my S3 bucket. From what I understand I should find a `letsencrypt` file and a `domain.example.com` file.

**Comment by fregante** [comment]
This is actually fixed by #14 on https://github.com/ubergeek42/lambda-letsencrypt/pull/14/commits/d0b853517a0ac9f29a881279ba090214d3af493b#diff-0e0960a956201021301746e32c810686R2
